
export const STATIC_PRODUCTS = [
  {
    id: 1,
    category: "vegteables",
    name: "Calabrese Broccoli",
    price: 20.0,
    dealPrice: 13.0,
    ratingStar: 5,
    imgUrl: "/brocolli.png",
  },
  {
    id: 2,
    category: "Fresh",
    name: "Fresh Banana Fruits",
    price: 20.0,
    dealPrice: 14.0,
    ratingStar: 5,
    imgUrl: "/banana.png",
  },
  {
    id: 3,
    category: "Millets",
    name: "White Nuts",
    price: 20.0,
    dealPrice: 15.0,
    ratingStar: 5,
    imgUrl: "/white_nuts.png",
  },
  {
    id: 4,
    category: "Health",
    name: "Mung Bean",
    price: 20.0,
    dealPrice: 11.0,
    ratingStar: 5,
    imgUrl: "/mung_bean.png",
  },
  {
    id: 5,
    category: "Nuts",
    name: "Brown Hazelnut",
    price: 20.0,
    dealPrice: 12.0,
    ratingStar: 5,
    imgUrl: "/hazelnut.png",
  },
  {
    id: 6,
    category: "Fresh",
    name: "Eggs",
    price: 20.0,
    dealPrice: 17.0,
    ratingStar: 5,
    imgUrl: "/eggs.png",
  },
  {
    id: 7,
    category: "Fruits",
    name: "Cucumber",
    price: 20.0,
    dealPrice: 11.0,
    ratingStar: 5,
    imgUrl: "/cucumber.png",
  },

  {
    id: 8,
    category: "Fresh",
    name: "Fresh Corn",
    price: 20.0,
    dealPrice: 17.0,
    ratingStar: 5,
    imgUrl: "/corn.png",
  },
];
